#spring:
#  cloud:
#    nacos:
#      config:
#        enabled: true
#  datasource:
#    url: jdbc:mysql://101.37.146.32:3306/onegene_infowork?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: geneuser
#    password: it123456
#    druid:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#server:
#  port: 8081
#management:
#  endpoint:
#    health:
#      show-details: always
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#
#mybatis:
#  mapper-locations: classpath*:mapper/*.xml
#  configuration:
#    map-underscore-to-camel-case: true
#
#logging:
#  config: classpath:logback-spring.xml
#
#nacos:
#  version: 3.0
#user:
#  name: 哈哈