# 此配置放nacos了 取名project-local.yml(${spring.application.name}-${spring.profile.active}.${spring.cloud.nacos.config.file-extension})
spring:
  cloud:
    nacos:
      config:
        enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/onegene_infowork?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: geneuser
    password: it123456
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  config: classpath:logback-spring.xml